export const answers = {
  zh: [
    "别失望",
    "不必为你无法控制的事情而担心",
    "不要忘记微笑",
    "阳光",
    "挥手道别",
    "你失去的某天会以不同的方式归还于你",
    "你的状态很不对",
    "这是个麻烦",
    "你或许需要突破",
    "放弃",
    "你唯一能做的只有把握现在",
    "学会珍惜",
    "改变心情",
    "一直走下去",
    "优秀",
    "坚持不懈的努力",
    "不适合",
    "愉快生活",
    "终点",
    "换一个方向",
    "岁月静好",
    "放轻松，这很简单",
    "早点儿开始",
    "不要后悔",
    "也许会迟到",
    "沉默",
    "好像平凡了点",
    "糊涂一点更好",
    "善待自己",
    "放手",
    "呼吸一下新鲜空气",
    "没有答案",
    "感恩，运气会越来越好",
    "原谅",
    "自我欣赏",
    "复杂的事情简单做",
    "学会自己保护自己",
    "奇迹",
    "给自己一个肯定",
    "甜",
    "摆正心态",
    "种下满足,收获幸福",
    "把握现在",
    "学会好奇",
    "最美丽的一天",
    "彼岸",
    "停止",
    "坚强",
    "永恒",
    "常常是最后一把钥匙打开了神殿门",
    "不要刻意隐藏",
    "停止悲伤",
    "不要刻意压抑",
    "背不动的就放下",
    "不要怕",
    "安静",
    "想念",
    "驻足静立",
    "活下去",
    "去爱",
    "回家",
    "未解之谜",
    "相遇",
    "陌生人",
    "告别",
    "本能",
    "取暖",
    "重逢",
    "不要去忘记",
    "自信起来吧",
    "爱",
    "接受那些消失的",
    "到此为止",
    "一步之遥",
    "保存",
    "虚无的关系",
    "时间有限",
    "迷失的世界",
    "慢下来",
    "可怕",
    "了不起",
    "一个正在到来的晴天",
    "好天气",
    "旧梦",
    "挽留",
    "逆水行舟",
    "被排挤",
    "可以期待的未来",
    "平平安安",
    "挥别错的",
    "朴素",
    "成为了事实",
    "萌芽",
    "有一些重要的事",
    "让你泪流满脸的",
    "不知所措",
    "给人依赖",
    "对未知前途的期盼",
    "用平淡的心态去追求",
    "一切皆有可能",
    "控制自己的情绪",
    "一切顺其自然",
    "一条没有鲜花的道路",
    "得不到别人的认同",
    "暂且不要判断",
    "不要一成不变",
    "学会认错",
    "你祈求的一切顺利",
    "享受全心全意的付出",
    "站在了最重要的地方",
    "捕风捉影",
    "欢天喜地",
    "轮回",
    "你无法继续沉睡",
    "得到了多数的支持",
    "十分好的预感",
    "背叛",
    "盛开",
    "学会改变什么",
    "最划算的交换",
    "退后一厘米",
    "这真是一个奇怪的问题",
    "用力活着",
    "成长",
    "最好的事情正要发生",
    "没有什么是对的",
    "堕落",
    "多余",
    "必须努力奔跑起来",
    "会有人陪着你",
    "驾驭",
    "站起来去战斗",
    "不要看轻别人",
    "多读一本书",
    "下一页才是你的人生答案",
    "出发",
    "差不多得了",
    "不要给人添麻烦",
    "一个人的细水长流",
    "左边",
    "有人浪费了你的时间",
    "最后什么都没改变",
    "对，去吧！",
    "扔掉这些东西",
    "有些人开始慌乱",
    "找回自己",
    "重生",
    "慢些，我们就会更快",
    "一个人的朝圣",
    "孤单",
    "下一个天亮",
    "独角戏",
    "平凡之路",
    "直面残酷",
    "泡沫",
    "你大概会受点伤",
    "远行",
    "一直在找什么",
    "回头看看",
    "唤醒沉睡的你",
    "也许会有好转",
    "烦恼快要消失了",
    "一无所有",
    "显得有些唐突",
    "迷人的危险",
    "结束倒计时",
    "第二次被伤害的机会",
    "并不会让你高兴",
    "没什么放不下",
    "等待",
    "等待",
    "永远不会愈合的伤口",
    "骗不到自己",
    "悄悄躲开",
    "一场完美的悲剧",
    "寻寻觅觅",
    "不要做出任何决定",
    "开心的肯定",
    "浪费光阴",
    "保密",
    "被唾弃的决定",
    "停止向前",
    "有点儿意思",
    "谢谢",
    "再也不要见",
    "完美时刻",
    "会让你痛苦的",
    "僵持不下",
    "必不可少",
    "对不起",
    "试着慷慨一点儿",
    "这不是能犹豫的事儿",
    "同意",
    "试着安静一会儿",
    "默默无闻",
    "虚空",
    "戒掉过分的急躁",
    "不要隐藏起来",
    "其实大家都知道",
    "会被一直依赖的",
    "全部给它",
    "坚持了不该坚持的",
    "你好像舍不得",
    "有点儿心疼",
    "轻而易举的伤害",
    "卑微的等待",
    "你有必要傻一点",
    "一成不变",
    "你会忘记它",
    "禁言",
    "只是一场梦",
    "你要勇敢的离开",
    "拼凑不了的昨天",
    "容易被操纵",
    "尽你最大的能力",
    "去忘记",
    "大家好像都不认同",
    "认真起来",
    "值得去做的事",
    "是",
    "白日梦",
    "转个身忘记吧",
    "你可能会比较悲伤",
    "这绝对是个好主意",
    "好的指引",
    "不是",
    "充满未知的迷惑",
    "光明的",
    "幼稚又可笑",
    "你很幸运",
    "机会就在眼前",
    "不如忘掉这个问题",
    "又干净又明亮",
    "专注一点",
    "殊途同归",
    "背道而驰",
    "小迷糊",
    "你在开玩笑吗",
    "别难过,你是最棒的",
    "吃点东西,冷静一下",
    "这个大概会让你哭泣",
    "高兴起来吧,你这么厉害",
    "别总想着过去了",
    "捍卫它",
    "无谓的徘徊",
    "将要被击溃",
    "不必耿耿于怀",
    "放在心里吧,这样比较好点",
    "不用伪装到面目全非",
    "不用担心,明天会更好",
    "等待最好的时机",
    "顺其自然吧",
    "别着急,会有解决的办法的",
    "是时候做出改变了",
    "相信你的直觉",
    "勇敢一点,面对挑战",
    "别害怕,一切都会好起来的",
    "重新开始",
    "保持乐观",
    "坚持就是胜利",
    "听听内心的声音",
    "享受当下的美好",
    "放松心情,别想太多",
    "往好的方面想",
    "不要放弃,希望就在前方",
    "给自己放个假",
    "多和朋友聊聊",
    "运动一下,释放压力",
    "看场电影,放松一下",
    "听听音乐,舒缓心情",
    "吃点甜食,让自己开心起来",
    "去旅行吧,看看外面的世界",
    "保持微笑,好运自然来",
    "相信自己,你是最棒的",
    "一切都会过去的",
    "时间会证明一切",
    "别为小事烦恼",
    "珍惜眼前人",
    "活在当下",
    "感恩生活",
    "保持谦虚",
    "不断学习",
    "勇于尝试",
  ],
  en: [
    "Don't be disappointed",
    "Don't worry about things you can't control",
    "Don't forget to smile",
    "Sunshine",
    "Wave goodbye",
    "What you have lost will be returned to you in a different way one day",
    "You are not in the right state",
    "This is a trouble",
    "You may need a breakthrough",
    "Give up",
    "The only thing you can do is to seize the present",
    "Learn to cherish",
    "Change your mood",
    "Keep walking",
    "Excellent",
    "Unremitting efforts",
    "Not suitable",
    "Happy life",
    "End point",
    "Change a direction",
    "The years are quiet",
    "Relax, it's easy",
    "Start early",
    "Don't regret",
    "Maybe late",
    "Silence",
    "It seems a bit ordinary",
    "It's better to be a little confused",
    "Be kind to yourself",
    "Let go",
    "Breathe fresh air",
    "No answer",
    "Thanksgiving, luck will get better and better",
    "Forgive",
    "Self-appreciation",
    "Do complex things simply",
    "Learn to protect yourself",
    "Miracle",
    "Give yourself an affirmation",
    "Sweet",
    "Correct your mindset",
    "Plant satisfaction, harvest happiness",
    "Seize the present",
    "Learn to be curious",
    "The most beautiful day",
    "The other side",
    "Stop",
    "Strong",
    "Eternity",
    "It is often the last key that opens the temple door",
    "Don't hide it deliberately",
    "Stop being sad",
    "Don't deliberately suppress",
    "Put down what you can't carry",
    "Don't be afraid",
    "Quiet",
    "Miss",
    "Stop and stand still",
    "Live",
    "Go to love",
    "Go home",
    "Unsolved mystery",
    "Encounter",
    "Stranger",
    "Farewell",
    "Instinct",
    "Warm up",
    "Reunion",
    "Don't forget",
    "Be confident",
    "Love",
    "Accept those that have disappeared",
    "So far",
    "One step away",
    "Save",
    "Nothingness relationship",
    "Time is limited",
    "Lost world",
    "Slow down",
    "Terrible",
    "Amazing",
    "A sunny day is coming",
    "Good weather",
    "Old dream",
    "Retention",
    "Sailing against the current",
    "Being excluded",
    "A future that can be expected",
    "Peace and safety",
    "Wave goodbye to the wrong",
    "Simple",
    "Became a fact",
    "Sprout",
    "There are some important things",
    "What makes you cry",
    "At a loss",
    "Give people dependence",
    "Expectations for the unknown future",
    "Pursue with a plain attitude",
    "Everything is possible",
    "Control your emotions",
    "Let it be",
    "A road without flowers",
    "Can't get recognition from others",
    "Don't judge for now",
    "Don't be stereotyped",
    "Learn to admit your mistakes",
    "Everything you pray for goes smoothly",
    "Enjoy the wholehearted dedication",
    "Standing in the most important place",
    "Catch the wind and catch the shadow",
    "Joyful",
    "Reincarnation",
    "You can't continue to sleep",
    "Get the support of the majority",
    "Very good premonition",
    "Betrayal",
    "Bloom",
    "Learn to change what",
    "The most cost-effective exchange",
    "Step back one centimeter",
    "This is really a strange question",
    "Live hard",
    "Growth",
    "The best thing is about to happen",
    "Nothing is right",
    "Fallen",
    "Superfluous",
    "Must run hard",
    "Someone will accompany you",
    "Control",
    "Stand up and fight",
    "Don't look down on others",
    "Read one more book",
    "The next page is the answer to your life",
    "Departure",
    "That's enough",
    "Don't cause trouble for others",
    "A person's long stream of water",
    "Left",
    "Someone wasted your time",
    "Nothing changed in the end",
    "Yes, go!",
    "Throw these things away",
    "Some people start to panic",
    "Find yourself",
    "Rebirth",
    "Slower, we will be faster",
    "A person's pilgrimage",
    "Lonely",
    "Next daybreak",
    "Monologue",
    "Ordinary road",
    "Face the cruel",
    "Bubble",
    "You will probably get hurt a little",
    "Travel far",
    "What have you been looking for",
    "Look back",
    "Wake up the sleeping you",
    "Maybe it will get better",
    "The trouble is about to disappear",
    "Have nothing",
    "It seems a bit abrupt",
    "Charming danger",
    "End countdown",
    "The second chance to be hurt",
    "It won't make you happy",
    "Nothing can't be let go",
    "Wait",
    "Wait",
    "A wound that will never heal",
    "Can't deceive yourself",
    "Quietly hide away",
    "A perfect tragedy",
    "Searching",
    "Don't make any decisions",
    "Happy affirmation",
    "Waste of time",
    "Keep secret",
    "A decision that is spurned",
    "Stop moving forward",
    "A bit interesting",
    "Thank you",
    "Never see again",
    "Perfect moment",
    "It will make you painful",
    "Stalemate",
    "Indispensable",
    "Sorry",
    "Try to be generous",
    "This is not something to hesitate about",
    "Agree",
    "Try to be quiet for a while",
    "Unknown",
    "Void",
    "Get rid of excessive impatience",
    "Don't hide",
    "In fact, everyone knows",
    "Will be relied on all the time",
    "Give it all",
    "Insisted on what should not be insisted on",
    "You seem to be reluctant",
    "A little distressed",
    "Easy harm",
    "Humble waiting",
    "You need to be a little silly",
    "Unchanged",
    "You will forget it",
    "Mute",
    "It's just a dream",
    "You have to leave bravely",
    "Yesterday that can't be pieced together",
    "Easy to be manipulated",
    "Do your best",
    "Go to forget",
    "Everyone seems to disagree",
    "Get serious",
    "Something worth doing",
    "Yes",
    "Daydream",
    "Turn around and forget it",
    "You may be sadder",
    "This is definitely a good idea",
    "Good guidance",
    "No",
    "Full of unknown confusion",
    "Bright",
    "Naive and ridiculous",
    "You are lucky",
    "The opportunity is right in front of you",
    "It's better to forget this question",
    "Clean and bright",
    "Focus a little",
    "Different paths lead to the same goal",
    "Run in the opposite direction",
    "Little confused",
    "Are you kidding me",
    "Don't be sad, you are the best",
    "Eat something and calm down",
    "This will probably make you cry",
    "Cheer up, you are so amazing",
    "Don't always think about the past",
    "Defend it",
    "Pointless wandering",
    "Will be defeated",
    "Don't have to worry about it",
    "Put it in your heart, it's better this way",
    "Don't have to disguise until it's unrecognizable",
    "Don't worry, tomorrow will be better",
    "Wait for the best time",
    "Let it be",
    "Don't worry, there will be a solution",
    "It's time to make a change",
    "Trust your intuition",
    "Be brave and face the challenge",
    "Don't be afraid, everything will be fine",
    "Start over",
    "Stay optimistic",
    "Persistence is victory",
    "Listen to your inner voice",
    "Enjoy the beauty of the moment",
    "Relax, don't think too much",
    "Think on the bright side",
    "Don't give up, hope is ahead",
    "Give yourself a vacation",
    "Talk more with friends",
    "Exercise and release stress",
    "Watch a movie and relax",
    "Listen to music and soothe your mood",
    "Eat some sweets to make yourself happy",
    "Go travel and see the outside world",
    "Keep smiling, good luck will come naturally",
    "Believe in yourself, you are the best",
    "Everything will pass",
    "Time will prove everything",
    "Don't worry about small things",
    "Cherish the people in front of you",
    "Live in the moment",
    "Grateful for life",
    "Stay humble",
    "Keep learning",
    "Be brave to try",
  ]
};
